fix: Move from git-tags to git-semver-tags
boxfish-studio/fontana pull request #39
Opened 2022-11-03 10:02 UTC by marc2332

Closes https://github.com/boxfish-studio/fontana/issues/38

## Changes

  - Migrate from git-tags to git-semver-tags
  - Removed duplicated code
  
### Checks

* [x] Have you catchup your branch with the latest state in base?
* [x] Have you lint your code locally prior to submission?
* [x] Have you reviewed your proposed changes and removed debris?
* [x] Have you successfully ran due tests with your changes?

2022-11-07 11:39 UTC, begonaalvarezd requested changes
we should be able to do it without dependencies

2023-01-17 12:16 UTC, marc2332 commented
What do you think about this approach? I have made some tests and it seems to work just fine. It takes the tag from the most closest tagged commit in the current branch

2023-01-25 16:29 UTC, aspnxdd approved these changes
Clean :fire:

2023-01-25 16:34 UTC, begonaalvarezd approved these changes

2023-01-25 16:35 UTC, merged